// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SM2.Web.Data;

namespace SM2.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191025160539_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SM2.Web.Data.Disability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("TypeLoansId");

                    b.Property<DateTime>("finalDate");

                    b.Property<DateTime>("initialDate");

                    b.Property<int>("typeDisability");

                    b.HasKey("Id");

                    b.HasIndex("TypeLoansId");

                    b.ToTable("Disabilities");
                });

            modelBuilder.Entity("SM2.Web.Data.Entities.Cesantia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("TypeCesantiasId");

                    b.Property<float>("Value");

                    b.Property<int>("typeCesantia");

                    b.HasKey("Id");

                    b.HasIndex("TypeCesantiasId");

                    b.ToTable("Cesantias");
                });

            modelBuilder.Entity("SM2.Web.Data.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CitiesId");

                    b.Property<int?>("TransferId");

                    b.Property<string>("nameCity");

                    b.HasKey("Id");

                    b.HasIndex("CitiesId");

                    b.HasIndex("TransferId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("SM2.Web.Data.Entities.License", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("TypeLicensesId");

                    b.Property<DateTime>("finalDate");

                    b.Property<DateTime>("initialDate");

                    b.Property<int>("typeDisability");

                    b.HasKey("Id");

                    b.HasIndex("TypeLicensesId");

                    b.ToTable("Licenses");
                });

            modelBuilder.Entity("SM2.Web.Data.Entities.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TypeLoan");

                    b.Property<int?>("TypeLoansId");

                    b.Property<float>("ValorLoan");

                    b.HasKey("Id");

                    b.HasIndex("TypeLoansId");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("SM2.Web.Data.Entities.Rep", b =>
                {
                    b.Property<int>("rep_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("directivo");

                    b.Property<int>("gerente");

                    b.Property<int>("gestiona_tiquetes");

                    b.Property<int>("pais");

                    b.Property<int>("proyecto");

                    b.Property<int>("ractivo");

                    b.Property<int>("rcargo");

                    b.Property<int>("rceco");

                    b.Property<int>("rcedula");

                    b.Property<string>("rcodigo")
                        .HasMaxLength(20);

                    b.Property<int>("rdependencia");

                    b.Property<int>("relacion_laboral");

                    b.Property<string>("remail")
                        .HasMaxLength(50);

                    b.Property<int>("rempresa");

                    b.Property<int>("resp_aviatur");

                    b.Property<int>("resp_formacion");

                    b.Property<int>("resp_plan_e_e");

                    b.Property<int>("resp_prestamos");

                    b.Property<int>("resp_th");

                    b.Property<int>("resp_traslados");

                    b.Property<string>("rextension")
                        .HasMaxLength(20);

                    b.Property<string>("rname")
                        .HasMaxLength(100);

                    b.Property<string>("rorden_interna")
                        .HasMaxLength(20);

                    b.Property<int>("rsede");

                    b.Property<int>("rtipo");

                    b.Property<string>("ruid")
                        .HasMaxLength(50);

                    b.Property<int>("tipo_regimen_salarial");

                    b.Property<string>("url_foto")
                        .HasMaxLength(100);

                    b.HasKey("rep_id");

                    b.ToTable("Reps");
                });

            modelBuilder.Entity("SM2.Web.Data.Entities.Transfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("City");

                    b.HasKey("Id");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("SM2.Web.Data.Entities.TypeCesantia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name");

                    b.HasKey("Id");

                    b.ToTable("TypeCesantias");
                });

            modelBuilder.Entity("SM2.Web.Data.Entities.TypeDisability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name");

                    b.HasKey("Id");

                    b.ToTable("TypeDisabilities");
                });

            modelBuilder.Entity("SM2.Web.Data.Entities.TypeLoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("TypeLoans");
                });

            modelBuilder.Entity("SM2.Web.Data.TypeLicense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name");

                    b.HasKey("Id");

                    b.ToTable("TypeLicenses");
                });

            modelBuilder.Entity("SM2.Web.Data.Disability", b =>
                {
                    b.HasOne("SM2.Web.Data.Entities.TypeDisability", "TypeLoans")
                        .WithMany("Disabilities")
                        .HasForeignKey("TypeLoansId");
                });

            modelBuilder.Entity("SM2.Web.Data.Entities.Cesantia", b =>
                {
                    b.HasOne("SM2.Web.Data.Entities.TypeCesantia", "TypeCesantias")
                        .WithMany("Cesantias")
                        .HasForeignKey("TypeCesantiasId");
                });

            modelBuilder.Entity("SM2.Web.Data.Entities.City", b =>
                {
                    b.HasOne("SM2.Web.Data.Entities.City", "Cities")
                        .WithMany()
                        .HasForeignKey("CitiesId");

                    b.HasOne("SM2.Web.Data.Entities.Transfer")
                        .WithMany("Cities")
                        .HasForeignKey("TransferId");
                });

            modelBuilder.Entity("SM2.Web.Data.Entities.License", b =>
                {
                    b.HasOne("SM2.Web.Data.TypeLicense", "TypeLicenses")
                        .WithMany()
                        .HasForeignKey("TypeLicensesId");
                });

            modelBuilder.Entity("SM2.Web.Data.Entities.Loan", b =>
                {
                    b.HasOne("SM2.Web.Data.Entities.TypeLoan", "TypeLoans")
                        .WithMany("Loans")
                        .HasForeignKey("TypeLoansId");
                });
#pragma warning restore 612, 618
        }
    }
}
